export const mockShopifyCheckout = {
  completedAt: null,
  createdAt: new Date().toISOString(),
  currencyCode: 'USD',
  email: '',
  lineItemsSubtotalPrice: { amount: 100000, currencyCode: 'USD' },
  note: null,
  order: null,
  orderStatusUrl: null,
  ready: true,
  requiresShipping: true,
  shippingAddress: null,
  shippingLine: null,
  subtotalPrice: { amount: 100000, currencyCode: 'USD' },
  taxExempt: false,
  taxesIncluded: false,
  totalPrice: { amount: 100000, currencyCode: 'USD' },
  totalTax: { amount: 0, currencyCode: 'USD' },
  updatedAt: new Date().toISOString(),
  webUrl: '',
  discountApplications: [],
  customAttributes: [],
  userErrors: [],
  completed: false,
  paymentDue: { amount: 0, currencyCode: 'USD' },
  paymentDueV2: { amount: 0, currencyCode: 'USD' },
  phone: '',
  presentmentCurrencyCode: 'USD',
  shippingDiscountAllocations: [],
  shippingLineHandle: '',
  subtotalPriceV2: { amount: 100000, currencyCode: 'USD' },
  totalDuties: null,
  totalPriceV2: { amount: 100000, currencyCode: 'USD' },
  totalTaxV2: { amount: 0, currencyCode: 'USD' },
  appliedGiftCards: [],
  buyerIdentity: {
    countryCode: null,
    email: '',
    phone: '',
    customer: null,
    deliveryAddressPreferences: [],
  },
};
