export default [
  {
    id: 1,
    orderId: 'WIGO-00001',
    price: 399000,
    createdAt: '2020-02-11 07:02:42',
    state: 'sent',
    cover: 'blue',
    name: 'Lee Lane',
    occupation: 'Doctor, Chef, Musician',
    gender: 'boy',
    age: 'toddler',
    skin: 'light',
    hair: 'curly',
  },
  {
    id: 2,
    orderId: 'WIGO-00001',
    price: 399000,
    createdAt: '2020-02-11 07:02:42',
    state: 'pending',
    cover: 'blue',
    name: 'Lee Lane',
    occupation: 'Doctor, Chef, Musician',
    gender: 'boy',
    age: 'toddler',
    skin: 'light',
    hair: 'curly',
  },
  {
    id: 3,
    orderId: 'WIGO-00001',
    price: 399000,
    createdAt: '2020-02-11 07:02:42',
    state: 'received',
    cover: 'blue',
    name: 'Lee Lane',
    occupation: 'Doctor, Chef, Musician',
    gender: 'boy',
    age: 'toddler',
    skin: 'light',
    hair: 'curly',
  },
];
