/* eslint-disable @typescript-eslint/camelcase */
export default [
  {
    id: 1,
    order_id: 'WIGO-00001',
    price: 399000,
    created_at: '2008-01-10T11:00:00-05:00',
    state: 'sent',
    cover: 'blue',
    name: 'Lee Lane',
    occupation: 'Doctor, Chef, Musician',
    gender: 'boy',
    age: 'toddler',
    skin: 'light',
    hair: 'curly',
  },
  {
    id: 2,
    order_id: 'WIGO-00001',
    price: 399000,
    created_at: '2008-01-10T11:00:00-05:00',
    state: 'pending',
    cover: 'blue',
    name: 'Lee Lane',
    occupation: 'Doctor, Chef, Musician',
    gender: 'boy',
    age: 'toddler',
    skin: 'light',
    hair: 'curly',
  },
  {
    id: 3,
    order_id: 'WIGO-00001',
    price: 399000,
    created_at: '2008-01-10T11:00:00-05:00',
    state: 'received',
    cover: 'blue',
    name: 'Lee Lane',
    occupation: 'Doctor, Chef, Musician',
    gender: 'boy',
    age: 'toddler',
    skin: 'light',
    hair: 'curly',
  },
];
