import { BookPage, Occupation, Province, Testimonial } from 'store/master/types';

export const OCCUPATIONS = [
  { id: '1', name: 'Doctor', description: 'Heals patients', indonesia: 'Dokter' },
  { id: '2', name: 'Chef', description: 'Cooks food', indonesia: 'Koki' },
  { id: '3', name: 'Teacher', description: 'Educates students', indonesia: 'Guru' },
  { id: '4', name: 'Astronaut', description: 'Explores space', indonesia: 'Astronot' },
  { id: '5', name: 'Pilot', description: 'Flies planes', indonesia: 'Pilot' },
  { id: '6', name: 'Police', description: 'Maintains law and order', indonesia: 'Polisi' },
] as Occupation[];

export const BOOK_PAGES = [
  {
    occupation: {
      id: '1',
      name: 'Front Cover',
    },
    occupation_id: 1,
    page_number: 1,
    englishText: 'When [name] Grows Up',
    indonesiaText: 'When [name] Grows Up',
    style: '{"top": "15%","color": "white","fontWeight": "bolder"}',
  },
  {
    occupation: { id: '1', name: 'intro', description: 'Heals patients' },
    occupation_id: 2,
    page_number: 1,
    englishText: 'Lorem ipsum dolor sit amet',
    indonesiaText: 'Contoh teks bahasa Indonesia',
  },
  {
    occupation: { id: '1', name: 'intro', description: 'Heals patients' },
    occupation_id: 2,
    page_number: 2,
    englishText: 'Lorem ipsum dolor sit amet',
    indonesiaText: 'Contoh teks bahasa Indonesia',
  },
  {
    occupation: { id: '1', name: 'intro', description: 'Heals patients' },
    occupation_id: 2,
    page_number: 3,
    englishText: 'Lorem ipsum dolor sit amet',
    indonesiaText: 'Contoh teks bahasa Indonesia',
  },
  {
    occupation: { id: '1', name: 'intro', description: 'Heals patients' },
    occupation_id: 2,
    page_number: 4,
    englishText: 'Lorem ipsum dolor sit amet',
    indonesiaText: 'Contoh teks bahasa Indonesia',
  },
  {
    occupation: OCCUPATIONS[0],
    occupation_id: 3,
    page_number: 1,
    englishText: 'Lorem ipsum dolor sit amet',
    indonesiaText: 'Contoh teks bahasa Indonesia',
  },
  {
    occupation: OCCUPATIONS[0],
    occupation_id: 3,
    page_number: 2,
    englishText: 'Lorem ipsum dolor sit amet',
    indonesiaText: 'Contoh teks bahasa Indonesia',
  },
  {
    occupation: OCCUPATIONS[1],
    occupation_id: 4,
    page_number: 1,
    englishText: 'Lorem ipsum dolor sit amet',
    indonesiaText: 'Contoh teks bahasa Indonesia',
  },
  {
    occupation: OCCUPATIONS[1],
    occupation_id: 4,
    page_number: 2,
    englishText: 'Lorem ipsum dolor sit amet',
    indonesiaText: 'Contoh teks bahasa Indonesia',
  },
  {
    occupation: OCCUPATIONS[2],
    occupation_id: 5,
    page_number: 1,
    englishText: 'Lorem ipsum dolor sit amet',
    indonesiaText: 'Contoh teks bahasa Indonesia',
  },
  {
    occupation: OCCUPATIONS[2],
    occupation_id: 5,
    page_number: 2,
    englishText: 'Lorem ipsum dolor sit amet',
    indonesiaText: 'Contoh teks bahasa Indonesia',
  },
] as BookPage[];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Sarah Johnson',
    company: 'Parent of Emma, Age 6',
    message:
      'This personalized book made my daughter feel like the hero of her own adventure. She asks to read it every night!',
    image_url: '/static/images/testimonial-1.jpg',
  },
  {
    id: 2,
    name: 'Michael Chen',
    company: 'Father of two',
    message: 'Amazing quality and storytelling. My kids love seeing themselves in the book. Highly recommend!',
    image_url: '/static/images/testimonial-2.jpg',
  },
] as Testimonial[];

export const PROVINCES = [
  { code: 'jakarta', name: 'Jakarta' },
  { code: 'west-java', name: 'West Java' },
  { code: 'central-java', name: 'Central Java' },
  { code: 'east-java', name: 'East Java' },
  { code: 'bali', name: 'Bali' },
  { code: 'sumatra', name: 'Sumatra' },
  { code: 'kalimantan', name: 'Kalimantan' },
  { code: 'sulawesi', name: 'Sulawesi' },
  { code: 'papua', name: 'Papua' },
  { code: 'ntt', name: 'Nusa Tenggara Timur' },
  { code: 'ntb', name: 'Nusa Tenggara Barat' },
  { code: 'maluku', name: 'Maluku' },
  { code: 'aceh', name: 'Aceh' },
  { code: 'bengkulu', name: 'Bengkulu' },
  { code: 'jambi', name: 'Jambi' },
  { code: 'lampung', name: 'Lampung' },
  { code: 'riau', name: 'Riau' },
  { code: 'kepulauan-riau', name: 'Kepulauan Riau' },
  { code: 'bangka-belitung', name: 'Bangka Belitung' },
  { code: 'sumatera-utara', name: 'Sumatera Utara' },
  { code: 'sumatera-barat', name: 'Sumatera Barat' },
  { code: 'dki-jakarta', name: 'DKI Jakarta' },
  { code: 'yogyakarta', name: 'Yogyakarta' },
  { code: 'banten', name: 'Banten' },
  { code: 'west-sumatra', name: 'West Sumatra' },
  { code: 'south-sumatra', name: 'South Sumatra' },
  { code: 'north-sumatra', name: 'North Sumatra' },
  { code: 'west-kalimantan', name: 'West Kalimantan' },
  { code: 'south-kalimantan', name: 'South Kalimantan' },
  { code: 'east-kalimantan', name: 'East Kalimantan' },
  { code: 'central-kalimantan', name: 'Central Kalimantan' },
  { code: 'north-kalimantan', name: 'North Kalimantan' },
  { code: 'gorontalo', name: 'Gorontalo' },
  { code: 'north-sulawesi', name: 'North Sulawesi' },
  { code: 'central-sulawesi', name: 'Central Sulawesi' },
  { code: 'south-sulawesi', name: 'South Sulawesi' },
  { code: 'southeast-sulawesi', name: 'Southeast Sulawesi' },
  { code: 'west-sulawesi', name: 'West Sulawesi' },
  { code: 'maluku-utara', name: 'Maluku Utara' },
  { code: 'papua-barat', name: 'Papua Barat' },
  { code: 'papua-selatan', name: 'Papua Selatan' },
  { code: 'papua-tengah', name: 'Papua Tengah' },
] as Province[];
