import { BookPage, Occupation } from 'store/master/types';

export const OCCUPATIONS = [
  { id: '1', name: 'Doctor', description: 'Heals patients', indonesia: 'Dokter' },
  { id: '2', name: 'Chef', description: 'Cooks food', indonesia: 'Koki' },
  { id: '3', name: 'Teacher', description: 'Educates students', indonesia: 'Guru' },
  { id: '4', name: 'Astronaut', description: 'Explores space', indonesia: 'Astronot' },
  { id: '5', name: 'Pilot', description: 'Flies planes', indonesia: 'Pilot' },
  { id: '6', name: 'Police', description: 'Maintains law and order', indonesia: 'Polisi' },
] as Occupation[];

export const BOOK_PAGES = [
  {
    occupation: {
      id: '1',
      name: 'Front Cover',
    },
    order: 1,
    occupation_id: 1,
    page_number: 1,
    englishText: 'When [name] Grows Up',
    indonesiaText: 'When [name] Grows Up',
    style: '{"top": "15%","color": "white","fontWeight": "bolder"}',
  },
  {
    occupation: { id: '1', name: 'intro', description: 'Heals patients' },
    order: 2,
    occupation_id: 2,
    page_number: 1,
    englishText: 'Page 1 content',
    indonesiaText: 'Konten Halaman 1',
  },
  {
    occupation: { id: '1', name: 'intro', description: 'Heals patients' },
    order: 2,
    occupation_id: 2,
    page_number: 2,
    englishText: 'Page 1 content',
    indonesiaText: 'Konten Halaman 1',
  },
  {
    occupation: { id: '1', name: 'intro', description: 'Heals patients' },
    order: 1,
    occupation_id: 2,
    page_number: 3,
    englishText: 'Page 1 content',
    indonesiaText: 'Konten Halaman 1',
  },
  {
    occupation: { id: '1', name: 'intro', description: 'Heals patients' },
    order: 1,
    occupation_id: 2,
    page_number: 4,
    englishText: 'Page 1 content',
    indonesiaText: 'Konten Halaman 1',
  },
  {
    occupation: { id: '1', name: 'Doctor', description: 'Heals patients' },
    order: 1,
    occupation_id: 3,
    page_number: 1,
    englishText: 'Page 1 content',
    indonesiaText: 'Konten Halaman 1',
  },
  {
    occupation: { id: '1', name: 'Doctor', description: 'Heals patients' },
    order: 1,
    occupation_id: 3,
    page_number: 2,
    englishText: 'Page 2 content',
    indonesiaText: 'Konten Halaman 2',
  },
  {
    occupation: { id: '2', name: 'Chef', description: 'Cooks food' },
    order: 2,
    occupation_id: 4,
    page_number: 1,
    englishText: 'Page 1 content',
    indonesiaText: 'Konten Halaman 1',
  },
  {
    occupation: { id: '2', name: 'Chef', description: 'Cooks food' },
    order: 2,
    occupation_id: 4,
    page_number: 2,
    englishText: 'Page 2 content',
    indonesiaText: 'Konten Halaman 2',
  },
  {
    occupation: {
      id: '3',
      name: 'Teacher',
      description: 'Educates students',
    },
    order: 3,
    occupation_id: 5,
    page_number: 1,
    englishText: 'Page 3 content',
    indonesiaText: 'Konten Halaman 3',
  },
  {
    occupation: {
      id: '3',
      name: 'Teacher',
      description: 'Educates students',
    },
    order: 3,
    occupation_id: 5,
    page_number: 2,
    englishText: 'Page 3 content',
    indonesiaText: 'Konten Halaman 3',
  },
] as BookPage[];
